create table JEXOS_USERS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  LOGIN_ID varchar(50) NOT NULL DEFAULT '',
  PASSWORD varchar(20) NOT NULL,
  STATUS char(1) NOT NULL DEFAULT '',
  PRIMARY KEY (ID)
);

create table JEXOS_CURRENCY_PRICE (USD DECIMAL unique, DATE_UPDATED TIMESTAMP not null default current_timestamp on update current_timestamp);

create table JEXOS_CURRENT_BALANCE(BALANCE DECIMAL(64, 18), START_BLOCK BIGINT);

ALTER TABLE JEXOS_CURRENT_BALANCE CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

ALTER TABLE JEXOS_CURRENT_BALANCE ADD START_BLOCK BIGINT;

create table JEXOS_TRANSACTIONS (TX_HASH VARCHAR(8000), TX_DATA VARCHAR(8000), LOGIN_ID VARCHAR(256), ID NUMERIC, JEXOS_CREDITED DECIMAL(64, 18), JEXOS_USD_VALUE_ON_DATE DECIMAL(64, 18), UNITS_PURCHASED DECIMAL(64, 18), GAS_LIMIT DECIMAL(64, 18), GAS_PRICE DECIMAL(64, 18), TX_COST DECIMAL(64, 18), TRANSACTION_DATE DATETIME, HYB_IMPORTED_DATE TIMESTAMP not null default current_timestamp on update current_timestamp, START_BLOCK BIGINT);

ALTER TABLE JEXOS_TRANSACTIONS CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
